apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 6h
  releaseName: cert-manager
  targetNamespace: cert-manager

  chart:
    spec:
      chart: cert-manager
      version: v1.19.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager-repo
        namespace: cert-manager
      interval: 12h

  install:
    createNamespace: false
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    crds:
      enabled: true
