apiVersion: v1
data:
    BASE_URL: ENC[AES256_GCM,data:b+ejRs/8P/35W0R+KlRi2uRUNkURgvhQXSa4aaybL9M5tkvk,iv:+vuhwBlGpcFKbs8Q3YvI5aPkwc8Fckr+0mJF/lKE84U=,tag:r1B0GDxh1tM5bhcRC8Fxog==,type:str]
    SMTP_AUTH_STRATEGY: ENC[AES256_GCM,data:UztLBQ==,iv:AjA2iWoXL1x7NE5VyCA97rlwHB2kExnvyQI3yFjFgqM=,tag:NXiZ+xGids/BYtpO6n7Bjw==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:W8hPCpsbCWUZnTxZAUX92eOPIhPZN4+ngPpz+w==,iv:+vJj36NvKnynqO1HzdbotFiXJqohBsQ/X5OebqazX4g=,tag:5dweTU8WYsIza9OBoXkdvQ==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:PmEG8RREnZE=,iv:7Z/zwE6ELaa9qpmVumpG4UcNrnew2qrx+WibQHYnm58=,tag:/uQdE3JxhCED+Js/nDClKQ==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:WbdsrBF8X60x4PUo4qtD+mwtE9r8uy2v,iv:sSIOTwX7d0RHiHnTmDHzm9K+F3tIK5EiqKn+eoTfFdE=,tag:sIWCc0IHQamRptJ8cPgSfw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:qzRCUrPL0ZBOlGuF9o/vRol6DLIDpsvfKiVL87LL8egK5/Rp82InOnCPKCHma75JN+iRyAxGFhdenx3LOkxDb+f0E+I=,iv:FXpd1RQQo9G2e7ti1YEy/5eEWvFsXq6uic8z4otQXa8=,tag:Co2WcKCRr0jXqSu/OV8ppA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:WaCLJw==,iv:EYoYd4/UH1uh3IpQ9iXHIliVm7ldNLxe1mLyeArjQ6E=,tag:YFKtqF6kmdj4tv10mQJmGg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:Y85YI8CIsjHP+UcFYE2Y3PraZoq10DkQK7DCCJF+Rtnlj2ip4RWASyP8WP2qtuHyQPDajinMp9uC/3jXDcbODN2Eg7ETNAGlqHySdJES2MY=,iv:HDIFgJmb1sQ/3/6+5QcenacdjmIaXIedP5S29mQ9y5o=,tag:G4rCJHsTB5cT2IOXbaPBKg==,type:str]
kind: Secret
metadata:
    name: mealie-container-env
sops:
    age:
        - recipient: age1sj99kupy552w8el4m2nydhpy89d5d7t968944dzac5xpu0k98duq8lqcf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYyt1bWRQWXRKREpYUDEv
            Vmc5Y09BSDRWeFp3bUl4UXM5SHprcUJ0QWdvClY3WFdCZHZ5dGFOWVUvNmZ1WGd5
            eHJMMkJnNjU1YjNTcEowbUdDd21Hbm8KLS0tIEVYdENvc3hzaXBzajdHckhCd1J6
            Tm9xVU9HMDdOQmRRa1l1UEVubXJFWTQK8QtrsSfj+8z6UYuyn1AS4aqUpPP68fIR
            VxPK++AFqS+rQdGtoAW62/YWmW39ajVUbhyRVUr1HBpzF0Vnbo9AbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T06:59:22Z"
    mac: ENC[AES256_GCM,data:L0vaZfJp9rNDIpvX8FkkeUfooJvEC7Gf5eYXyKLwi0EQXsqO0w5o2HOZTJmIOWv83T0YBhKvFxvSeEGZ+/fAnPY524N+boXYo/ZAL//INzaO+QqNEc3jHmR80C6zvpdICXeQyBj3PRXKu/wgt0PrhigDzJD+kTCbKgGcGv/Ws+g=,iv:K7nMvNtZ7o99CznpnLKfE6UNthFZdwMIreqDn2coz4I=,tag:3LyRrkuJPJwOZKgvvk1GUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
