apiVersion: v1
data:
    BASE_URL: ENC[AES256_GCM,data:uXi4u0RLuwge8xhPoKQgkGAuN9RtSB6HADNc7CQ0inm70mWm,iv:PYTblhVE+tQdCDqbpxQt2FP4n91EkkhirN/opI6WWw8=,tag:fJsbY/yDqAl33QC/o0Vysg==,type:str]
    SMTP_AUTH_STRATEGY: ENC[AES256_GCM,data:LdCvVA==,iv:EScJwPHnwudBxYsJQFGTyrZenJuFmzU+YLiZhXBJ5zc=,tag:oBaC4vL+SRfbpCLlj9KZEQ==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:Ur2V/tY7F7wi6/YF//w0COLLvIdwEKLIn6MpCaB6pvM=,iv:nHrkIy3GX5eXdgvqaEuJ3gf+3/ERddGlrD+1BvhKxE4=,tag:EGkSqaHHo6xxloDJvWkzQA==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:rvjK+sCpH6U=,iv:CiKWngdute3XWcFlc1LkPJfCw5CzF8CGDTjCwfpVGew=,tag:FqquxgYkhvdhUfIhGB8R8g==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:eetoe62TpzVZMjFS3ZAzJh04RdypxGwh,iv:Nl/PAtIr1678Mf7f9rjChT4ut3ioRvxjW7De2KjIka0=,tag:YXJogIWxHaOTwQZ/FUDl4A==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:YF8OX53iV+2ah8klJ0Se/hpEA212miHAVL/pvZAeba+j8cNpZ6C76tao20pSieyUrmjAV5z38qk7BJccXV2oJvRrIwY=,iv:AU2W/C13RA/DmPe85zgYiVuQ5hKLAe750l6DnN4xkk0=,tag:CvOoN6+ctHmT6EkMp4Ns5Q==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:w71ZdA==,iv:MGUpsEtOadtNmMvKbNyUP7bhCWDsVncar1C+tgsUGAA=,tag:ocbhKM4FyYOOSf0ws8Rw9Q==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:ow85pGNrOs2610TSN4+sqKDa2XXeruKq+f6mwrzpJqdzxm36LgBRiWq4sQ18gfSgOkkAMr1zXBVQAKM6/3diigr5KUxDfUy1Tky1EpacKWs=,iv:2+vVWn2iIfRdKeEuJeL/uExi6kSQz2vqmYjjby6QSGo=,tag:I84B71I+fOzf2AaSFwBsqg==,type:str]
kind: Secret
metadata:
    name: mealie-container-env
sops:
    age:
        - recipient: age1sj99kupy552w8el4m2nydhpy89d5d7t968944dzac5xpu0k98duq8lqcf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaWx4eVZFN0xBUzlSZHg4
            aE9yTytNUTVkUmtvUjBOWG1WQlNOY3MyeUY0Ck9LMXlwZG5MOCtLNGJCSHkveXpB
            dkNHRTZkekpuZTdSWm93T3cwaW5tUU0KLS0tIGNxRmU5Vy9mczBMZ0lzMkwzZEZT
            Y0VvMnBoMU5aZSthRzFrSjVySEtWQmMKGur8hLQ1e425NZSVLi0I2UTlBy2sxpvN
            L1CVEqo2XX+bFY1u1kPw+SnRfS68rmWQTPK2/Q9gi+8V4JAYVjnqWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T07:45:21Z"
    mac: ENC[AES256_GCM,data:RUz/FjY/vvGE+9QhKeIzgnhTyiFzwKDs1JIR8y6wHc0/SetyX/yEZvOYNeCsB2WE4j+7OlCkgRojawa8XXS8/Ph6kkEjc6enLsl55ZQJL29tcEpwa4OsvEMwH1uidGou0a5I2w8fbFyfmBWqcEG2xX1T4Uhfz0us+XmL4o0BeMA=,iv:mTfF6O9vYHpthIf/PJyqLZmve3qjI7Z4PwU0dJ8s9WA=,tag:AV2Mak056lkfraH21RLfqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
