apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: infrastructure
spec:
  interval: 6h
  releaseName: metallb
  targetNamespace: infrastructure
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb-repo
        namespace: infrastructure
      interval: 12h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values: {}
