apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: mealie
spec:
  storageClassName: qnap-nfs
  accessModes:
#    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
