apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 6h
  releaseName: reflector
  targetNamespace: reflector

  chart:
    spec:
      chart: reflector
      version: 9.1.45
      sourceRef:
        kind: HelmRepository
        name: reflector-repo
        namespace: reflector
      interval: 12h

  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values: {}
