apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:5eFxPBkg5q8a7fcLBIzG6oVgbnbgZmJ8AW7cG2sP5FMcPxyPgzuDglG5kYPjuaQONkic1mGdmmvWvsLlmkI8miiuY/QbRCy9Bdg41/UO379xCQ9SG6PzsjPoHH5XxDqCddWJ9unqXRAXOxTgr6/LVmfcO80p+FYvg8HlrxhBqxmHeggbFBc215+cBLllDl2e46XFtauhaw48JWSBLkSGt36td4Fr6adg/Eyq2N5pecpLHHo+,iv:EPKWqKE0KBYYyi7RWMdSCXr8CK531VMtCKnUnBg7Ma0=,tag:/SlCl7oXVU/mtDbPgj6HPw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1sj99kupy552w8el4m2nydhpy89d5d7t968944dzac5xpu0k98duq8lqcf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZGZLV3ZLQ2IrNVgrYnlr
            NlFMK3dldVQyNWtVbXlrVitTSTI2OUVSNGk0CjhZZ0VKZGpDQ1lMV0xMdnE0bkJH
            dnkxQ1ZBTWFBM2RQajlFWnBSeTlFeGcKLS0tIHdzeGQ5Yit6ZldDVUJjRUN3Ujhw
            MHdYQWZyemVFdiswNFdpYnhnVUhCTWsKUMzaR5ryHFKVXOdc2Bqr1dt3hrZDmaVu
            jUuH7zloHVUxJLIJ6VAfJFYlj1C+i9Nf0u27GWGFKW0FIi//lUdK5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T21:21:51Z"
    mac: ENC[AES256_GCM,data:/l4ssRPy/avO82rPryI4GdOj+WCFG8dTa6Wua/mtW8d8WHKRkV7V+kkxaU3UAY09vDLrswzywRfTWKCh9r/dwOzIUz0K5N5WmYL1Biw+iz65Oxai9ELG8BH3Q9AlIJ1xSdUHr5WAQsbunRkLOkhc9P0Yvm2mE8GDTpcp09P6TRI=,iv:UxeKamQzv7Ok5Hj58FjI92Prc7jW8iU4wO9rWcn+2N8=,tag:H9kdGI9327P8UG0iJmA5/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
