apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:3qjt7KkqG1VZxTDUtIABXlkcX11K13wTOH53ILtyebQtKrLl5CaiBY786zS52+kdVMKgJflfbunqKVKXkQwcKzhpV1dh+abji1Guxy/5Ltq6Ui8yxh8TeCSEY53vxUcBzclSu5d1vC4aJSF/uPWRtaY9Zx7+V/LbfETagpCrM7l7hx7btnJ2f/g2rnNxp6RHW/+4JAamU8gO6wL/2hh/oZKIGEMpaqYTwmBls4proUS2KhQlkaf6GzJiESEgtDva3tJqFzHux4Qv/QpTWFecyQ7KCvr9p9X2okJbxhDCX5Yr8mdm4KVwxiazjB0=,iv:IUVwA2Sn5yH94GviPJyQmghky5LoioqfGXtwmS3D2Zg=,tag:s+rSZG0mDgvdPBFoChWCTw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1sj99kupy552w8el4m2nydhpy89d5d7t968944dzac5xpu0k98duq8lqcf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OEhFRURCTnVMelZCRnFq
            Q3pmWE41RUhzcjhnVmJpSUtRT0ladEEzbVhJCm5hTXJuRlJybm9vWThhUDExQlo1
            TEtoSFBCL0tBbWdHVHJMd3crQjNIVTAKLS0tIHdsdnVxNC9DYWMvck0zUzhYUGpU
            SS9pTUg4MmY4eHZHZFdKdjVsWGI2UVkKOZkG8BBB42pgrF59URChgqXhNRiwDKiG
            21A4FRhPnlTDq8KYyQwVBSCBNL0mFTi40DzfTUZrTF3z5oPgVmBqsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T21:44:02Z"
    mac: ENC[AES256_GCM,data:N0CAHv1Nh5mOUDqjyR+tUOI6GPO+1bbYcVAcdrjMEImdHAGqeW8gfm/5KF+tggGpm9KwnCW/WwlRvlkFvTzeUIcm2IWtstllhZJERjLoqHlNgV/gf0usvxUPeK0peR+FgwEj3yqeJ7kbAjvm25R7rF4VBR0d+N4gEykVMdlgL2k=,iv:E4w/sgghx3BC7DhKYmotyJ5gjGhgytoUOGM9oYWThgo=,tag:KKhHVpYtnKK0vhnjeGfYcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
