apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:r/IvxQ==,iv:TM1LMhf0iLGP1KlRW0mbZO0kLxZClW2ldKUH+fXtvsg=,tag:muM0XxeZbCu7AonPOpJtJA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:rscj0srrK7oL97CT,iv:LCtEXfc3qgJqohIYWill3wtSHrJA2Al2KQsZjmALjT4=,tag:V0w9wwAN4jDMlUp+FzhbFg==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1sj99kupy552w8el4m2nydhpy89d5d7t968944dzac5xpu0k98duq8lqcf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZUNMRVM2YlZCSUtYK1Vp
            ZnY1Q2NGWWxBNHlyT0hGL3hFZUNHSFQ1dHc0CkIrQ2pvcEw5RXpza1ErODE0YVFB
            dFZ4RGRIZXd0V1M5V2RFZElBVE40QlEKLS0tIFJHNm1zOTdPMzE2VzFZNENQdVMx
            K1RPRUI4cG1LSG5lVzYwZ3NRK3NvamcKAY4afETLSw4AKs/K7DR2swHWggC5qhzV
            UTF2Sbs/jT//k/CsqnYniQ8DpLyYTqhxgIvnnPVEbrPeFlL2WLkwmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T21:33:42Z"
    mac: ENC[AES256_GCM,data:fZuXm4mgUl6QobmMZmLi6pMcjbFhcNIA0N3dIlJXYdc6u9aaNkYRWzvdfCHpgcvuQ3/9xqgfoRUmFvZhs0gjnJT8Qrv3RhSYsCEqL+uoQbsJs9KVR/c0EdyvJGsJAU3sqAIXp+T+8IYcyN8GFdvymY8BvrdL/6iBjOHqpfvfqWE=,iv:CYK21fHi4ZGbtN9fy9WLr9+Ik46EaL+qLwKmzIY3q78=,tag:f2mwkR3GH/6xG3yBHfjPuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
