apiVersion: v1
data:
    password: ENC[AES256_GCM,data:8UMfFUud3XfbKzWeIzSrime1qQs=,iv:htqGwCWoz2g4m9pdUfZaTegBTcXG5CIO7lUeKrYArTo=,tag:NUGiKuw/Osx33LzR75MEfw==,type:str]
    user: ENC[AES256_GCM,data:hzPko5POks4=,iv:MleVH0ETYWs4Sz1KNnPLXSXAYMyV2mLYLDPXG3j6gsM=,tag:VV9kOh0ZMU45P1nXYCRzKA==,type:str]
kind: Secret
metadata:
    name: user-secret
sops:
    age:
        - recipient: age1sj99kupy552w8el4m2nydhpy89d5d7t968944dzac5xpu0k98duq8lqcf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySlk5cVdJUTBibVdVTklP
            UmV5b1MvYTNjZ0dFeE9EYWNvWXpwSGFCWkZZClBHTjUzeDdYZ0xLdGsrKzFzZjNF
            QWswZVZycUVLdmhkbGN1eXJNOHoxS0kKLS0tIDJ0YlFNWHRyVCsrT2orZUFPc1F1
            azhteCtTSHhscjJ0UjdxUnl5NDN5MDQKIWjUsopNWxYcTsewOOUyHFlNYgVHNQzp
            Cmluey2mZNca1nFmgB5hLD/tss7dUsqXXVu8v1WWoLU+ZXMIxRtd9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T17:38:01Z"
    mac: ENC[AES256_GCM,data:qCj3pp0TK8ZHDEQyJOr1TdalbnWJUjPJ05wAspwnuuKQnAhgwlDe/2HTMz3Vo1ptbVsnSUxoa1rZ8z7uWtmCA10I0W9JTnBywAXAtr65899ROCTtA6O2h9Cb4rVbKJg70nK5KFzo7vLx6NTIXFyvqYA26PolpzgxwXhvYrqY4tc=,iv:CpHsc7TrWxiVBWsp7Ah8D/7wf7TWEFg8MqFSLn0JiwU=,tag:nuNYYpertPqQ/JiZtQoOsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
