apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data2-pvc
  namespace: linkding
spec:
  storageClassName: qnap-nfs
  accessModes:
    - ReadWriteMany
  #accessModes:
    #- ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
