apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-subdir-provisioner
spec:
  interval: 6h
  releaseName: nfs-subdir-external-provisioner
  targetNamespace: nfs-subdir-provisioner
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: nfs-subdir-provisioner
      interval: 12h
  values:
    nfs:
      server: 192.168.20.10
      path: /dev
      # Optional: set mount options if you want to force NFS version, etc.
      mountOptions:
        - nfsvers=4.1

    storageClass:
      name: qnap-nfs
      defaultClass: false
      reclaimPolicy: Delete
      allowVolumeExpansion: true

      # Since this is NFS, RWX is usually what you want:
      accessModes: ReadWriteMany

      # Delete/retain behavior for the subdirectory when PVC is deleted:
      archiveOnDelete: false
      onDelete: delete