apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale-repo
        namespace: tailscale
      interval: 1h

  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

  valuesFrom:
    - kind: Secret
      name: tailscale-operator-oauth
      valuesKey: values.yaml